---
title: "EDS 221 Day 3 Comp"
format: html
editor: visual
execute: 
  warning: FALSE
---

### Conditional statements

```{r}
temp <- 95

if (temp > 97) {
  print("temperature warning")
} else
  print("no warning")
```

create an if else statement for blue whale lengths. Create a variable blue whale with a value of 40. add an if else statement that returns "giant" if the length exceeds 35, medium if the length is between 20 and 35, small if the length is less than 20

```{r}
blue_whale <- 30

if (blue_whale > 35) {
  print("GIANT")
} else if (blue_whale >= 20 & blue_whale <= 35) {
  print("MEDIUM")
} else if (blue_whale < 20) {
  print("SMALL")
}
```

### Switch statement

```{r}
housing_type <- "whole"

switch(housing_type,
       "single" = print(400),
       "double" = print(750),
       "whole" = print(1100))

if (housing_type == "single") {
  print(400)
} else if (housing_type == "double") {
  print(750)
} else if (housing_type == "whole") {
  print(1100)
}
```

## for loops

```{r}
height <- c(58, 61, 65, 72, 89, 94)

for (i in seq_along(height)) {
  half_height = height[i] / 2
  print(half_height)
}

## for each value in height vector, return sum of value + the one right after it

heighta <- c(3, 5, 8, 72, 89, 94)

for (i in seq_along(heighta)) {
  height2 = heighta[i] + heighta[i + 1]
  print(height2)
}
```

```{r}
## write a for loop that calculates value of height for each element divided by the mean of the entire height vector

for (i in seq_along(height)) {
  height_st = height[i] / mean(height)
  print(height_st)
}
```
